### ISSUE TITLE
question about windows level

### ISSUE THREAD

**Issue by iu0v1** [jroimartin/gocui#23]
Hello.

I made some roughing (but working well) code to close issue [#3](https://github.com/jroimartin/gocui/issues/3).

But with an independent View'ers redraw, I have  a some troubles with the windows hierarchy.
If we create, for example, first window (at level "0") and second on top of previous (at level "1"), then inactive "top level" window may fall through under level "0" (in situation, when level "0" need redraw, and level "1" dosen' need, but we want level "1" on top).

I see several solutions to this situation:
1. add "window level" politic (windows can have some "window level" option, and redrawn based on these rules);
2. or add simple "always on top" rule;

I need a strong opinion of the author of the project :)

PS: sorry for my bad English

**Comment by jroimartin** [comment]
Hi,

Some time ago I was also thinking about adding a "z" field to the View type. However, I discarded it due to most of the time when you create a new window which overlaps others, it is because you want this last window on top.

So, IMO I would follow the "always on top" rule. Of course, if you can find a good example of a common situation where a "window level" politic would be needed, please share and we can discuss about adding this to gocui :)

BTW (quick reminder) please use the v0.2-dev branch for your patch.

Thanks!
