### ISSUE TITLE
DeleteView() should remove the associated key bindings with the view

### ISSUE THREAD

**Issue by dcu** [jroimartin/gocui#32]
It seems like delete view is not removing the associated key bindings and it causes issues on dynamic UIs.

**Comment by jroimartin** [comment]
Keybindings are assigned at Gui level, not at View level. So, I feel that deleting a View should not affect to keybindings. What about adding a new function like the next one?
```
func (g *Gui) DeleteKeybinding(viewname string, key interface{}, mod Modifier) error
```

**Comment by dcu** [comment]
What's the purpose of a key binding on a view that should no longer exist?
I think it's confusing and hard to debug.

**Comment by jroimartin** [comment]
Sorry for my really really late response. One case could be, for instance, this one:  https://github.com/jroimartin/gocui/blob/master/_examples/demo.go#L105

**Comment by jroimartin** [comment]
Closed due to inactivity. Feel free to reopen if you want to continue the discussion.

**Comment by leerumler** [comment]
Looks like I'm a little late to the party, but I would love to see the ability to delete keybindings implemented.  I'm currently working on a project, and I found myself needing to create six views that are almost entirely identical because I need to set different keybindings on each of them.  None of the views should ever be active at the same time, so being able to re-use that view with different keybindings would really simplify the code.

**Comment by jroimartin** [comment]
Hi @leerumler,

I've just added *Gui.DeleteKeybinding in 2a0623774fea2f2326126a71f1099a0a395e004c. Is it enough? :)

**Comment by leerumler** [comment]
Sorry for the late response on this, but yeah, that will work perfectly!  Thank you!
