### ISSUE TITLE
View Title Alignment

### ISSUE THREAD

**Issue by shibukraj** [jroimartin/gocui#38]
Hi,
Using the gocui for creating a Terminal application. We have a main view more like a dialog which we would like to set the title. Right now the title comes to the left end of the layout. Any way to add the alignment for the title, so that it aligns to the middle?

**Comment by jroimartin** [comment]
Hi @shibukraj,

Right now only left alignment is supported. And, to be honest, I'd prefer to keep gocui as simple as possible. Because, for me, a minimalist API is a must.

In the case of the titles, they were introduced because, otherwise, you'd need to have 2 synchronized views if you wanted to show a title per view (1 view for the contents + 1 view w/o frame for the title), which adds complexity when using the package. But, I don't really see a rationale behind adding title formatting to gocui, other than aesthetics. For instance, it would add another data type like `Alignment` (`AlignLeft`, `AlignCenter`, `AlighRight`), a field like `*View.TitleAlignment`, etc.

**Comment by shibukraj** [comment]
Hi jroimartin

Thanks for the very fast response. I totally understand the need to keep it as a minimalist API. I am new to golang and learning the language as I develop the application using gocui. Also very much thankful for the explanation of the need for title as well. Thanks again. Really appreciate it.
