### ISSUE TITLE
Handling the ESCape key

### ISSUE THREAD

**Issue by phf** [jroimartin/gocui#47]
At first I was confused why your demos all exit on CTRL-C instead of ESC. Then I noticed that any handler I install for KeyEsc will be ignored. I eventually traced this back to gocui hardcoding the termbox.InputAlt input mode in the MainLoop method in gui.go. If I hack the code to set termbox.InputEsc instead, I get the behavior I want. My first instinct is that this should be the application's choice, not gocui's. However, I may be missing something about what gocui needs in order to work. Any hints?

**Comment by jroimartin** [comment]
Hi @phf,

On one hand, I hardcoded it to avoid adding "tricky" options to the gocui's API, making it simple for the users.

On the other hand, I chose `inputMode := termbox.InputAlt` because I think it's more "compatible". From the termbox-go documentation:

```
    1. Esc input mode. When ESC sequence is in the buffer and it doesn't
    match any known sequence. ESC means KeyEsc. This is the default input
    mode.

    2. Alt input mode. When ESC sequence is in the buffer and it doesn't
    match any known sequence. ESC enables ModAlt modifier for the next
    keyboard event.
```

I always remember having troubles depending on the terminal emulator to make the ALT/META key works. So, you always used 'ESC+' instead or ended up mapping ALT/META to ESC+. The same happens in OSX and, for instance, iTerm2 recommends:

![image](https://cloud.githubusercontent.com/assets/1223476/14761516/e1634120-0963-11e6-81fd-8df428908c75.png)

So, for example, when you press "ALT+2", it will send ESC+2. To bind this combination in gocui, you can use:

```
if err := g.SetKeybinding("side", '2', gocui.ModAlt, nextView); err != nil {
                return err
}
```

Because it uses `termbox.InputAlt` by default. And, this is the rationale to take this decision.

**Comment by micronix** [comment]
I'm trying to create an editor interface similar to vim with a normal mode and an insert mode. It feels like it should be easy to do this, but when I bind j in ModAlt mode I have to press Esc every time. What am I missing?

```go
	if err := g.SetKeybinding("main", 'j', gocui.ModAlt, cursorDown); err != nil {
		return err
	}
```

**Comment by jroimartin** [comment]
@micronix please take a look in my previous comment. There you have the explanation to that.

**Comment by jroimartin** [comment]
Closed due to inactivity.

**Comment by gbitten** [comment]
This PR (https://github.com/jroimartin/gocui/pull/56) makes the KeyESC binding work correctly.
