### ISSUE TITLE
Reading buffer without carriage returns inserted by Wrap = true

### ISSUE THREAD

**Issue by jameycribbs** [jroimartin/gocui#53]
Hey!  First of all, thank you so much for an awesome library!  I have only been using it for a few days but I already have a version of my app working really well, thanks to how great your library is.

I am building a simple cui note taking app (https://github.com/jameycribbs/cribbnotes_cui).  So far, I've been able to get pretty much everything working that I want, but I have run into an issue when saving a note to a json file.  When I use the view.Buffer() method to grab the internal buffer, and I have view.Wrap=true, then the json file I save has all of the carriage returns that are getting inserted into the text because Wrap is set to true.

Is there any way to keep Wrap=true, but be able to grab the contents of the internal buffer without the carriage returns that are being inserted?

I took a look at the source code, but I didn't see a way to do this.  I'm  fairly new to Go, so I am probably missing something.

Thanks for any help you can give and thanks again for such a great library!

Jamey Cribbs

**Comment by jameycribbs** [comment]
So, I dug into the library code a little more and I see that in the Buffer() function, a "\n" is getting inserted at the end of every entry in v.lines as the output string is being built up.

I think that may be where the newlines are coming from when I call Buffer().

So, I guess my question is, if Buffer() is supposed to be an internal representation of the contents, why is are the newlines being inserted into the output of Buffer()?

Thanks for any info!

**Comment by jroimartin** [comment]
Hi Jamey!

I've just added a new example that saves the contents of a wrapping view in two different ways:

https://github.com/jroimartin/gocui/blob/master/_examples/save.go

If you press `C-s` it will save the internal buffer of the view (what you want) and with `C-w` it saves the visual representation of the buffer (what you see in the GUI, including wrapped lines).

As you can see, there are two functions that allows you to access the View's buffer:

* **\*View.Buffer()**: Buffer returns a string with the contents of the view's internal buffer.
* **\*View.ViewBuffer()**: ViewBuffer returns a string with the contents of the view's buffer that is shown to the user.

Regarding your question about `v.lines`, it is a `[][]cell` because it makes much easier the implementation. For instance, when translating from visual coordinates to a point in the internal buffer or when implementing wrapping. If you want, you can give a look to [*View.realPosition()](https://github.com/jroimartin/gocui/blob/master/view.go#L358) and how it is used in the code.

I hope to have answered your question :) If not, just let me know!

**Comment by jroimartin** [comment]
I've just edited my previous comment and added more details about the gocui internals related to your question.

**Comment by jroimartin** [comment]
OK! I've just found the bug that is affecting you. So, there are two scenarios:

1. In my example, I'm writing the contents of a file to a wrapping View and after resizing to get wrapped lines, when you save it, it just works fine not adding wrong newlines.

2. If you edit a wrapping view, there is a bug in the edition mode that split lines when you get to the end of the line, messing up in the internal buffer.

Now I understand your problem. I'll fix the bug ASAP :) Thanks for reporting!

**Comment by jameycribbs** [comment]
Thanks!  I am really having a great time with gocui.  I have already implemented a rudimentary vim-mode for editing notes (I'm a vim guy, so this is a big deal for me!).

**Comment by jroimartin** [comment]
Should be fixed now.

**Comment by jroimartin** [comment]
BTW I added [_examples/bufs.go](https://github.com/jroimartin/gocui/blob/8d16527c1d616dd5e9d09cf5f928489ece3c77e3/_examples/bufs.go) to easily test this. Just edit the view and press Ctrl+C to check the buffers.
