### ISSUE TITLE
Correctly handle invalid terminal dimensions

### ISSUE THREAD

**Issue by gsora** [jroimartin/gocui#85]
[My application](https://github.com/gsora/polo-lendbot) have the following layout:

![](http://i.imgur.com/KiHN1A8.png)

If the terminal size goes under 83x38, my application just crashes because the terminal has invalid dimensions.

This is probably due to the fact that if it's impossible to draw all the tabs on the screen, gocui assumes that it's not possible to draw anything at all?

What's the correct way to handle this situation?

**Comment by libeclipse** [comment]
You could make the dimensions relative to the window. So for example, if you want your top box to cover 75% of the screen, then (assuming `y = height of window`) the height of the box should be `y - (0.25 * y)`.

**Comment by jroimartin** [comment]
Actually, gocui should not crash under this situation. However, depending on how you define your layout, it could happen that `*Gui.SetView()` returns an error because the given coordinates are not valid.

For instance, in the following piece of code:

```go
if demands, err := g.SetView("demands", 0, 0, (maxX/2)-40, maxY-37); err != nil {
        ...
}
```
(https://github.com/gsora/polo-lendbot/blob/master/main.go#L146)

If `(maxX/2)-40` or `maxY-37` are `<= 0` then `*Gui.View()` will return an error because the dimensions are not invalid:

https://github.com/jroimartin/gocui/blob/master/gui.go#L128

So, you should take this into account when defining your layout.

**Comment by gsora** [comment]
Is `layout()` (my layout function) being called when the view is resized too?

**Comment by jroimartin** [comment]
Yes
